In [2]:
import nltk
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
s1=["Music is a fundamental attribute of the human species. Virtually all cultures, from the most primitive to the most advanced, make music. It's been true through history, and it's true throughout an individual's lifespan. In tune or not, we humans sing and hum; in time or not, we clap and sway; in step or not, we dance and bounce."]
s2=["The human brain and nervous system are hard-wired to distinguish music from noise and to respond to rhythm and repetition, tones and tunes. Is this a biologic accident, or does it serve a purpose? It's not possible to say. Still, a varied group of studies suggests that music may enhance human health and performance."]

In [4]:
# Vectors
vectorizer = CountVectorizer(stop_words='english')
# tokenize
vectorizer.fit(s1)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [5]:
#summary
print(vectorizer.vocabulary_)

{'music': 14, 'fundamental': 6, 'attribute': 1, 'human': 9, 'species': 17, 'virtually': 23, 'cultures': 4, 'primitive': 15, 'advanced': 0, 'make': 13, 'true': 21, 'history': 7, 'individual': 11, 'lifespan': 12, 'tune': 22, 'humans': 10, 'sing': 16, 'hum': 8, 'time': 20, 'clap': 3, 'sway': 19, 'step': 18, 'dance': 5, 'bounce': 2}


In [6]:
vector = vectorizer.transform(s1)

In [10]:
print(vector.shape)
print(type(vector))
print(vector.toarray())
v1=vector.toarray()

(1, 24)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 0 0 0 0 0 0 2 0 0 0 0 2 0 0 0 0 0 0 0 0 0]]


In [11]:
print(vectorizer.vocabulary_)

{'music': 14, 'fundamental': 6, 'attribute': 1, 'human': 9, 'species': 17, 'virtually': 23, 'cultures': 4, 'primitive': 15, 'advanced': 0, 'make': 13, 'true': 21, 'history': 7, 'individual': 11, 'lifespan': 12, 'tune': 22, 'humans': 10, 'sing': 16, 'hum': 8, 'time': 20, 'clap': 3, 'sway': 19, 'step': 18, 'dance': 5, 'bounce': 2}


In [12]:
vector = vectorizer.transform(s2)
print(vector.toarray())
v2=vector.toarray()

[[0 0 0 0 0 0 0 0 0 2 0 0 0 0 2 0 0 0 0 0 0 0 0 0]]


In [13]:
#Cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vec1,vec2)

array([[0.38729833]])

In [14]:
cosine_similarity(v1,v2)

array([[1.]])

In [15]:
#it has 38 cosine similarity. Cosine similarity can fall between 0 and 1. 

In [16]:
#If it is closer to 1, the given input is parallel. If it is closer to 0, the given input is perpendicular.

In [17]:
# Here it is perpendicular