In [1]:
#stopwords

In [2]:
from nltk.corpus import stopwords
stopwords.words('english')[:50]

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be']

In [3]:
from nltk.corpus import stopwords
stopwords.words('spanish')[:50]

['de',
 'la',
 'que',
 'el',
 'en',
 'y',
 'a',
 'los',
 'del',
 'se',
 'las',
 'por',
 'un',
 'para',
 'con',
 'no',
 'una',
 'su',
 'al',
 'lo',
 'como',
 'más',
 'pero',
 'sus',
 'le',
 'ya',
 'o',
 'este',
 'sí',
 'porque',
 'esta',
 'entre',
 'cuando',
 'muy',
 'sin',
 'sobre',
 'también',
 'me',
 'hasta',
 'hay',
 'donde',
 'quien',
 'desde',
 'todo',
 'nos',
 'durante',
 'todos',
 'uno',
 'les',
 'ni']

In [4]:
#cmud
import nltk
entries=nltk.corpus.cmudict.entries()
len(entries)

133737

In [5]:
entries[:100]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [6]:
#wordnet
from nltk.corpus import wordnet as wn
wn.synsets('honest')

[Synset('honest.a.01'),
 Synset('honest.s.02'),
 Synset('dependable.s.02'),
 Synset('honest.s.04'),
 Synset('honest.s.05'),
 Synset('good.s.19'),
 Synset('honest.s.07')]

In [7]:
wn.synset('honest.a.01').lemma_names()

['honest', 'honorable']

In [8]:
wn.synset('honest.s.05').lemma_names()

['honest']

In [9]:
wn.synset('honest.a.07').lemma_names()

['honest', 'fair']

In [10]:
def gender_features(word):
    return{'last_word':word[-1]}

In [11]:
gender_features('Diana')

{'last_word': 'a'}

In [12]:
nltk.download('names')
from nltk.corpus import names
labeled_names=([(name,'male') for name in names.words('male.txt')]+[(name,'female') for name in names.words('female.txt')])

[nltk_data] Downloading package names to
[nltk_data]     C:\Users\danto\AppData\Roaming\nltk_data...
[nltk_data]   Package names is already up-to-date!


In [13]:
import random
random.shuffle(labeled_names)

In [14]:
featuresets=[(gender_features(n),gender) for (n,gender) in labeled_names]

In [15]:
train_set,test_test=featuresets[:500],featuresets[:500]

In [16]:
import nltk
classifier=nltk.NaiveBayesClassifier.train(train_set)

In [17]:
classifier.classify(gender_features('Diana'))

'female'

In [18]:
#doesn't work for indian names
classifier.classify(gender_features('Ravi'))

'female'

In [19]:
#vector and cosine siilarity
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
#initialize
vect=CountVectorizer(binary=True)
corpus = ["Tessaract is good optical character recognition engine  ", "optical character recognition is significant "]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [21]:
#creating vocabolary
vocab=vect.vocabulary_

In [22]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [23]:
print(vect.transform(["This is a good optical illusion"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [24]:
print(vect.transform([" optical illusion and recognition is good"]).toarray())

[[0 0 1 1 1 1 0 0]]


In [25]:
print(vect.transform(["This is a good optical illusion"]))

  (0, 2)	1
  (0, 3)	1
  (0, 4)	1


In [26]:
#finding cosine similarity of s1 and s2
#vectorizing s1
s1=vect.transform(["This is a good optical illusion"]).toarray()

In [27]:
#vectorizing s2
s2=vect.transform(corpus).toarray()

In [28]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 1 1 0 1]
 [1 0 0 1 1 1 1 0]]


In [29]:
#finding cosine similarity
similarity = cosine_similarity(s1,s2)

NameError: name 'cosine_similarity' is not defined